# Generated by Django 2.2.2 on 2019-06-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('dir', models.TextField()),
            ],
        ),
    ]
