# Generated by Django 2.2.2 on 2019-06-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkpage', '0004_auto_20190617_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleitem',
            old_name='desc',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='lessonitem',
            old_name='grade',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='newsitem',
            old_name='date',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='personitem',
            old_name='desc',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='placeitem',
            old_name='desc',
            new_name='q2',
        ),
    ]
