# Generated by Django 2.2.2 on 2019-06-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitem',
            name='parkcode',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
